// TODO: Nessa V1, vamos usar o react-icons para os ícones, a ideia é que na V2 possamos usar icones proprios

import {
  FiAlertCircle,
  FiAlertTriangle,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiCamera,
  FiCheck,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiClock,
  FiDollarSign,
  FiEdit,
  FiEye,
  FiEyeOff,
  FiFile,
  FiFilter,
  FiGithub,
  FiGlobe,
  FiHeadphones,
  FiHeart,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiInfo,
  FiLock,
  FiLogOut,
  FiMail,
  FiMenu,
  FiMessageCircle,
  FiMinus,
  FiMoreHorizontal,
  FiMoreVertical,
  FiPaperclip,
  FiPlus,
  FiPower,
  FiRefreshCw,
  FiSave,
  FiSearch,
  FiSettings,
  FiShare2,
  FiShoppingBag,
  FiStar,
  FiTrash2,
  FiUser,
  FiUserPlus,
  FiUsers,
  FiX,
  FiXCircle
} from 'react-icons/fi';

export const Icons = {
  AlertCircle: FiAlertCircle,
  AlertTriangle: FiAlertTriangle,
  ArrowDown: FiArrowDown,
  ArrowLeft: FiArrowLeft,
  ArrowRight: FiArrowRight,
  ArrowUp: FiArrowUp,
  Camera: FiCamera,
  Check: FiCheck,
  CheckCircle: FiCheckCircle,
  ChevronDown: FiChevronDown,
  ChevronLeft: FiChevronLeft,
  ChevronRight: FiChevronRight,
  ChevronUp: FiChevronUp,
  Clock: FiClock,
  DollarSign: FiDollarSign,
  Edit: FiEdit,
  Eye: FiEye,
  EyeOff: FiEyeOff,
  File: FiFile,
  Filter: FiFilter,
  Github: FiGithub,
  Globe: FiGlobe,
  Headphones: FiHeadphones,
  Heart: FiHeart,
  Help: FiHelpCircle,
  Home: FiHome,
  Image: FiImage,
  Info: FiInfo,
  Lock: FiLock,
  LogOut: FiLogOut,
  Mail: FiMail,
  Menu: FiMenu,
  MessageCircle: FiMessageCircle,
  Minus: FiMinus,
  MoreHorizontal: FiMoreHorizontal,
  MoreVertical: FiMoreVertical,
  Paperclip: FiPaperclip,
  Plus: FiPlus,
  Power: FiPower,
  RefreshCw: FiRefreshCw,
  Save: FiSave,
  Search: FiSearch,
  Settings: FiSettings,
  Share2: FiShare2,
  ShoppingBag: FiShoppingBag,
  Star: FiStar,
  Trash2: FiTrash2,
  User: FiUser,
  UserPlus: FiUserPlus,
  Users: FiUsers,
  X: FiX,
  XCircle: FiXCircle
}; 